[package]
name = "cloc2flare"
version = "0.1.0"
authors = ["Korny Sietsma <korny@sietsma.com>"]
edition = "2018"

[dependencies]
tokei = "9.1.1"
ignore = "0.4"
serde = { version = "1.0.90",features = ["derive"] }
erased-serde = "0.3"
serde_json = "1.0"
regex = "1"
failure = "0.1.5"