[package]
name = "test_shared"
version = "0.0.1"
authors = ["Korny Sietsma <korny@sietsma.com>"]
description = "Shared test helpers for lati-scanner"
edition = "2018"

[dependencies]
serde = { version = "1.0.90",features = ["derive"] }
serde_json = "1.0"
regex = "1"
failure = "0.1.5"
failure-tools = "4.0.2"
tempfile = "3.0.8"
zip = "0.5.2"
pretty_assertions = "0.6.1"